version: "3.4"

services:
    identifier-publisher:
        image: semtech/mu-identifier:feature-websockets
        environment:
            SESSION_COOKIE_SECURE: "on"
            environment:
            DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: '[{"variables":[],"name":"public"}]'
        links:
            - dispatcher-publisher:dispatcher
        ports:
            - "80:80"
        networks:
            - ldes-network

    dispatcher-publisher:
        image: semtech/mu-dispatcher:feature-websockets
        links:
            - resource-publisher:resource
            - file-publisher:file
            - login-publisher:login
            - registration-publisher:registration
            - socialplatformwsmicroservice-publisher:socialplatformwsmicroservice
            - frontend-publisher:frontend
        volumes:
            - ./config/dispatcher:/config
        networks:
            - ldes-network

    database-publisher:
        image: semtech/mu-authorization:0.6.0-beta.7
        environment:
            MU_SPARQL_ENDPOINT: "http://triplestore-publisher:8890/sparql"
            ERROR_ON_UNWRITTEN_DATA: true
        links:
            - deltanotifier-publisher:deltanotifier
        volumes:
            - ./config/authorization:/config
        networks:
            - ldes-network

    triplestore-publisher:
        image: redpencil/virtuoso:1.0.0
        environment:
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "http://mu.semte.ch/application"
        ports:
            - "8890:8890"
        volumes:
            - ./data/db:/data
            - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
        networks:
            - ldes-network

    login-publisher:
        image: semtech/mu-login-service:2.9.1
        environment:
            USERS_GRAPH: "http://mu.semte.ch/graphs/users"
            SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
        links:
            - database-publisher:database
        networks:
            - ldes-network

    registration-publisher:
        build: ./registration-service
        environment:
            MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/users"
        links:
            - database-publisher:database
        networks:
            - ldes-network

    file-publisher:
        image: semtech/mu-file-service:3.2.0
        links:
            - database-publisher:database
        volumes:
            - ./data/files:/share
        networks:
            - ldes-network

    yasgui-publisher:
        image: erikap/yasgui
        ports:
            - 3000:80
        environment:
            DEFAULT_SPARQL_ENDPOINT: "http://localhost:8890/sparql"
            ENABLE_ENDPOINT_SELECTOR: true
        networks:
            - ldes-network

    resource-publisher:
        image: semtech/mu-cl-resources:1.21.0
        links:
            - database-publisher:database
        volumes:
            - ./config/resources:/config
        networks:
            - ldes-network

    deltanotifier-publisher:
        image: semtech/mu-delta-notifier
        volumes:
            - ./config/delta:/config
        links:
            - socialplatformwsmicroservice-publisher:socialplatformwsmicroservice
            - socialplatformmicroservice-publisher:socialplatformmicroservice

        networks:
            - ldes-network

    socialplatformmicroservice-publisher:
        image: semtech/mu-javascript-template
        environment:
            NODE_ENV: "development"
        links:
            - triplestore-publisher:database
        volumes:
            - ./socialplatform-microservice/:/app/
        networks:
            - ldes-network

    socialplatformwsmicroservice-publisher:
        image: semtech/mu-javascript-template
        environment:
            NODE_ENV: "development"
        links:
            - triplestore-publisher:database
        ports:
            - 3002:3000
        volumes:
            - ./socialplatform-ws-microservice/:/app/
        networks:
            - ldes-network

    frontend-publisher:
        image: danlynn/ember-cli:4.2.0
        volumes:
            - ./ember-mu-socialplatform:/myapp
        networks:
            - ldes-network

    imageservice-publisher:
        image: madnificent/mu-image-service:0.0.1
        links:
            - database-publisher:database
        volumes:
            - ./data/files:/share
        networks:
            - ldes-network

networks:
    ldes-network:
        name: ldes-network
