version: "3.4"

services:
    identifier:
        image: semtech/mu-identifier:feature-websockets
        environment:
            SESSION_COOKIE_SECURE: "on"
            environment:
            DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: '[{"variables":[],"name":"public"}]'
        ports:
            - "82:80"

    dispatcher:
        image: semtech/mu-dispatcher:feature-websockets
        volumes:
            - ./config/dispatcher:/config

    database:
        image: semtech/mu-authorization:0.6.0-beta.7
        environment:
            MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
            ERROR_ON_UNWRITTEN_DATA: true
        volumes:
            - ./config/authorization:/config

    triplestore:
        image: redpencil/virtuoso:1.0.0
        environment:
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "http://mu.semte.ch/application"
        ports:
            - "8891:8890"
        volumes:
            - ./data/db:/data
            - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini

    login:
        image: semtech/mu-login-service:2.9.1
        environment:
            USERS_GRAPH: "http://mu.semte.ch/graphs/users"
            SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"

    registration:
        build: ./registration-service
        environment:
            MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/users"

    file:
        image: semtech/mu-file-service:3.2.0
        volumes:
            - ./data/files:/share

    yasgui:
        image: erikap/yasgui
        ports:
            - 3001:80
        environment:
            DEFAULT_SPARQL_ENDPOINT: "http://localhost:8890/sparql"
            ENABLE_ENDPOINT_SELECTOR: true

    resource:
        image: semtech/mu-cl-resources:1.21.0
        volumes:
            - ./config/resources:/config

    deltanotifier:
        image: semtech/mu-delta-notifier
        volumes:
            - ./config/delta:/config

    socialplatformmicroservice:
        image: semtech/mu-javascript-template
        environment:
            NODE_ENV: "development"
        links:
            - triplestore:database
        volumes:
            - ./socialplatform-microservice/:/app/

    socialplatformwsmicroservice:
        image: semtech/mu-javascript-template
        environment:
            NODE_ENV: "development"
        links:
            - triplestore:database
        ports:
            - 3005:3000
        volumes:
            - ./socialplatform-ws-microservice/:/app/

    frontend:
        image: danlynn/ember-cli:4.2.0
        volumes:
            - ./ember-mu-socialplatform:/myapp

    imageservice:
        image: madnificent/mu-image-service:0.0.1
        volumes:
            - ./data/files:/share

    ldes-consumer-service:
        image: semtech/mu-javascript-template:feature-typescript-support
        environment:
            NODE_ENV: "development"
            MU_APPLICATION_GRAPH: "http://mu.semte.ch/ldes-posts"
            LOG_SPARQL_ALL: false
            DEBUG_AUTH_HEADERS: true
        volumes:
            - ./ldes-consumer-microservice/:/app/
        networks:
            - default
            - ldes-network

networks:
    ldes-network:
        name: ldes-network
