version: "3.4"

services:
    identifier-consumer:
        image: semtech/mu-identifier:feature-websockets
        environment:
            SESSION_COOKIE_SECURE: "on"
            environment:
            DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: '[{"variables":[],"name":"public"}]'
        links:
            - dispatcher-consumer:dispatcher
        ports:
            - "82:80"
        networks:
            - ldes-network

    dispatcher-consumer:
        image: semtech/mu-dispatcher:feature-websockets
        links:
            - resource-consumer:resource
            - file-consumer:file
            - login-consumer:login
            - registration-consumer:registration
            - socialplatformwsmicroservice-consumer:socialplatformwsmicroservice
            - frontend-consumer:frontend
        volumes:
            - ./config/dispatcher:/config
        networks:
            - ldes-network

    database-consumer:
        image: semtech/mu-authorization:0.6.0-beta.7
        environment:
            MU_SPARQL_ENDPOINT: "http://triplestore-consumer:8890/sparql"
            ERROR_ON_UNWRITTEN_DATA: true
        links:
            - deltanotifier-consumer:deltanotifier
        volumes:
            - ./config/authorization:/config
        networks:
            - ldes-network

    triplestore-consumer:
        image: redpencil/virtuoso:1.0.0
        environment:
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "http://mu.semte.ch/application"
        ports:
            - "8891:8890"
        volumes:
            - ./data/db:/data
            - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
        networks:
            - ldes-network

    login-consumer:
        image: semtech/mu-login-service:2.9.1
        environment:
            USERS_GRAPH: "http://mu.semte.ch/graphs/users"
            SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
        links:
            - database-consumer:database
        networks:
            - ldes-network

    registration-consumer:
        build: ./registration-service
        environment:
            MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/users"
        links:
            - database-consumer:database
        networks:
            - ldes-network

    file-consumer:
        image: semtech/mu-file-service:3.2.0
        links:
            - database-consumer:database
        volumes:
            - ./data/files:/share
        networks:
            - ldes-network

    yasgui-consumer:
        image: erikap/yasgui
        ports:
            - 3001:80
        environment:
            DEFAULT_SPARQL_ENDPOINT: "http://localhost:8890/sparql"
            ENABLE_ENDPOINT_SELECTOR: true
        networks:
            - ldes-network

    resource-consumer:
        image: semtech/mu-cl-resources:1.21.0
        links:
            - database-consumer:database
        volumes:
            - ./config/resources:/config
        networks:
            - ldes-network

    deltanotifier-consumer:
        image: semtech/mu-delta-notifier
        volumes:
            - ./config/delta:/config
        networks:
            - ldes-network
        links:
            - socialplatformwsmicroservice-consumer:socialplatformwsmicroservice
            - socialplatformmicroservice-consumer:socialplatformmicroservice

    socialplatformmicroservice-consumer:
        image: semtech/mu-javascript-template
        environment:
            NODE_ENV: "development"
        links:
            - triplestore-consumer:database
        volumes:
            - ./socialplatform-microservice/:/app/
        networks:
            - ldes-network

    socialplatformwsmicroservice-consumer:
        image: semtech/mu-javascript-template
        environment:
            NODE_ENV: "development"
        links:
            - triplestore-consumer:database
        ports:
            - 3005:3000
        volumes:
            - ./socialplatform-ws-microservice/:/app/
        networks:
            - ldes-network

    frontend-consumer:
        image: danlynn/ember-cli:4.2.0
        volumes:
            - ./ember-mu-socialplatform:/myapp
        networks:
            - ldes-network

    imageservice-consumer:
        image: madnificent/mu-image-service:0.0.1
        links:
            - database-consumer:database
        volumes:
            - ./data/files:/share
        networks:
            - ldes-network

    ldes-consumer-service:
        image: semtech/mu-javascript-template:feature-typescript-support
        environment:
            NODE_ENV: "development"
            MU_APPLICATION_GRAPH: "http://mu.semte.ch/ldes-posts"
            LOG_SPARQL_ALL: false
            DEBUG_AUTH_HEADERS: true
        links:
            - database-consumer:database
        volumes:
            - ./ldes-consumer-microservice/:/app/
        networks:
            - ldes-network

networks:
    ldes-network:
        name: ldes-network
